### ISSUE TITLE
Loading more pages from api???

### ISSUE THREAD

**Issue by Inside4ndroid** [ahmedorabi94/Movies-TV-Shows-Guide#3]
Hi. 

Firstly awsome work on the application :)

i have been testing the functions etc of the application but i am having issues on loading page 2, 3, 4 etc when user scrolls to end of recyclerview in main movies and tv shows fragment...

i did notice that there is a getnextpage function in the ApiResponse.java file but i cannot seem to implement it...

any help or suggestions would be great

**Comment by ahmedorabi94** [comment]
you need to use Paging library, I am not using it in this projects.

**Comment by Inside4ndroid** [comment]
thanks for the reply :)
